name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/gh-pages.yml"
      - "docs/**"
      - "global_opt_bench/**"
      - "tests/**"

jobs:
  pages:
    runs-on: ai-runners
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3