name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ai-runners
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          # Install Python
          apt-get update
          apt-get install -y python${{ matrix.python-version }}
          apt-get install -y python3-venv
          
          # Create virtual environment
          python${{ matrix.python-version }} -m venv .venv
          
          # Add virtual environment to PATH
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          
          # Upgrade pip
          .venv/bin/pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install .
      - name: Lint with ruff
        run: |
          python -m pip install ruff
          ruff check .
      - name: Test with pytest
        run: |
          python -m pip install pytest
          pytest